export const TOLERANCE = 6

export const CIRCLE_HANDLE_SIZE = 5
export const SQUARE_HANDLE_SIZE = 5

export const HitTestConstants = {
    HOVER_LINE_TOLERANCE: TOLERANCE,
    EDIT_LINE_TOLERANCE: TOLERANCE,
    HANDLE_RADIUS: TOLERANCE,
    HANDLE_TOLERANCE: TOLERANCE,
}
